"""user auth token for reset password

Revision ID: d3a02055a1de
Revises: a9e561e03a68
Create Date: 2017-02-18 19:16:42.061210

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd3a02055a1de'
down_revision = 'a9e561e03a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_token')
    # ### end Alembic commands ###
