"""rename tables

Revision ID: d502cfd729d6
Revises: 4699e18f3fc1
Create Date: 2017-03-21 00:43:35.656647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd502cfd729d6'
down_revision = '4699e18f3fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('periodic_task', 'tasks')
    op.rename_table('interval', 'intervals')
    op.rename_table('crontab', 'crontabs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('tasks', 'periodic_task')
    op.rename_table('intervals', 'interval')
    op.rename_table('crontabs', 'crontab')
    # ### end Alembic commands ###
